bridge:
    enabled: true
    max-length: 32
    allowed-materials: [4, 5, 22, 24, 35, 41, 42, 44, 45, 48, 57, 80]
gate:
    enabled: true
    max-length: 32
    max-width: 3
door:
    enabled: true
    max-height: 32
    allowed-materials: [4, 5, 22, 24, 35, 41, 42, 45, 47, 48, 49, 57, 80]
hidden-switch:
    enabled: true
lift:
    enabled: true
    max-search-height: 32
ammeter:
    enabled: true
cauldron:
    enabled: true
# Add your recipes here. The index is the name of the recipe. Ingredients and results are noted as [id, amount].
    recipes:
        Glowstone:
            # 4 dirt, 4 torches
            ingredients: [ [3,4], [50,4] ]
            # 8 glowstone
            results: [ [89,8] ]
        Hellstone:
            # 4 cobble, 4 torches
            ingredients: [ [4,4], [50,4] ]
            # 8 hellstone
            results: [ [87,8] ]
        Soulsand:
            # 4 cobble, 4 sand
            ingredients: [ [4,4], [12,4] ]
            # 8 soulsand
            results: [ [88,8] ]
        Sponge:
            # 4 gold blocks
            ingredients: [ [41,4] ]
            # 8 sponge
            results: [ [19,8] ]
        Pumpkin:
            # 4 hellstone, 4 farmland
            ingredients: [ [87,4], [60,4] ]
            # 1 pumpkin
            results: [ [86,1] ]
pen:
    enabled: true
    material: 263

use-permissions: true
use-worldguard: false
use-zones: false