name: BetterMechanics
main: com.edoxile.bukkit.bettermechanics.BetterMechanics
version: 1.7a
author: Edoxile
website: https://github.com/Edoxile/BetterMechanics
commands:
  pen:
    description: Change the text of signs
    usage: /pen <clear|set|setline|help>